services:
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      ports:
        - 8080:8080
      command: start-dev
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
